# Generated by Django 2.0.3 on 2018-09-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_validation', models.CharField(max_length=250)),
                ('question_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reconnaissance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionCategory', to='Campus.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_department', models.CharField(max_length=100)),
                ('user_rollno', models.IntegerField(default=0)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.IntegerField(default=0)),
                ('user_address', models.CharField(max_length=200)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Role')),
            ],
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='answer_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Status'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Question'),
        ),
        migrations.AddField(
            model_name='reconnaissance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionSection', to='Campus.Section'),
        ),
    ]
