# Generated by Django 2.0.3 on 2018-08-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_department', models.CharField(max_length=100)),
                ('user_rollno', models.IntegerField(default=0)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.IntegerField(default=0)),
                ('user_address', models.CharField(max_length=200)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campus.Role')),
            ],
        ),
    ]
