# Generated by Django 2.0.3 on 2018-09-05 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_Icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
