# Generated by Django 2.0.3 on 2018-09-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0002_category_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_Icon',
            new_name='category_icon',
        ),
    ]
