# Generated by Django 2.0.2 on 2018-09-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0002_auto_20180830_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionCategory', to='Campus.Category'),
        ),
    ]
