# Generated by Django 2.0.3 on 2018-10-19 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0004_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconnaissance',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
