# Generated by Django 2.0.2 on 2018-11-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0006_auto_20181022_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campus.UserStatus'),
        ),
    ]
